-- V11: Product Attribute Seed Data
-- DEPRECATED: Old hand-written product_attribute mappings removed.
-- All product attributes are now generated via data/transform_backup_data.py
-- and inserted in V14__additional_categories_and_attributes.sql
-- This file is kept as a no-op to preserve Flyway migration history.
