-- ============================================
-- Generated product data
-- Generated on 2025-11-17T20:25:53
-- ============================================
BEGIN;

-- ===== cpu (CPU) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'AMD Ryzen 7 9800X3D', '8C/4.7GHz Zen 5', 11288000.00, 20, 5, (SELECT id FROM categories WHERE name = 'CPU'), '{"name":"AMD Ryzen 7 9800X3D","price":451.5,"core_count":8,"core_clock":4.7,"boost_clock":5.2,"microarchitecture":"Zen 5","tdp":120,"graphics":"Radeon","brand":"AMD","source_file":"cpu.jsonl","source_category":"CPU"}'::jsonb, '{"manufacturer":"AMD","series":"AMD Ryzen 7","generation":null,"socket":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'AMD Ryzen 7 9800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'AMD Ryzen 7 7800X3D', '8C/4.2GHz Zen 4', 8501000.00, 20, 5, (SELECT id FROM categories WHERE name = 'CPU'), '{"name":"AMD Ryzen 7 7800X3D","price":340.05,"core_count":8,"core_clock":4.2,"boost_clock":5,"microarchitecture":"Zen 4","tdp":120,"graphics":"Radeon","brand":"AMD","source_file":"cpu.jsonl","source_category":"CPU"}'::jsonb, '{"manufacturer":"AMD","series":"AMD Ryzen 7","generation":null,"socket":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'AMD Ryzen 7 7800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU'));

-- ===== memory (Memory) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Corsair Vengeance RGB 32 GB', '2 x 16GB DDR5-6000', 2375000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Memory'), '{"name":"Corsair Vengeance RGB 32 GB","price":94.99,"speed":[5,6000],"modules":[2,16],"price_per_gb":2.968,"color":"Black","first_word_latency":12,"cas_latency":36,"brand":"Corsair","source_file":"memory.jsonl","source_category":"Memory"}'::jsonb, '{"manufacturer":"Corsair","type":null,"capacity":4,"bus_speed":null,"ecc":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Corsair Vengeance RGB 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'G.Skill Flare X5 32 GB', '2 x 16GB DDR5-6000', 2250000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Memory'), '{"name":"G.Skill Flare X5 32 GB","price":89.99,"speed":[5,6000],"modules":[2,16],"price_per_gb":2.812,"color":"Black","first_word_latency":12,"cas_latency":36,"brand":"G.Skill","source_file":"memory.jsonl","source_category":"Memory"}'::jsonb, '{"manufacturer":"G.Skill","type":null,"capacity":8,"bus_speed":null,"ecc":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'G.Skill Flare X5 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory'));

-- ===== video-card (Video Card) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'MSI GeForce RTX 3060 Ventus 2X 12G', 'GeForce RTX 3060 12GB', 7499000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Video Card'), '{"name":"MSI GeForce RTX 3060 Ventus 2X 12G","price":299.97,"chipset":"GeForce RTX 3060 12GB","memory":12,"core_clock":1320,"boost_clock":1777,"color":"Black","length":235,"brand":"MSI","source_file":"video-card.jsonl","source_category":"Video Card"}'::jsonb, '{"manufacturer":"MSI","memory_type":null,"memory_size":2,"memory_bus":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'MSI GeForce RTX 3060 Ventus 2X 12G' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Sapphire PULSE', 'Radeon RX 9060 XT', 9500000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Video Card'), '{"name":"Sapphire PULSE","price":379.99,"chipset":"Radeon RX 9060 XT","memory":16,"core_clock":2220,"boost_clock":3290,"color":"Black","length":240,"brand":"Sapphire","source_file":"video-card.jsonl","source_category":"Video Card"}'::jsonb, '{"manufacturer":"Sapphire","memory_type":null,"memory_size":2,"memory_bus":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Sapphire PULSE' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card'));

COMMIT;
